version: '2'

services:
  website:
    env_file:
      - ./flask.env
    build:
      context: ..
      dockerfile: ./deployment/flask/Dockerfile
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp
    command: uwsgi --ini uwsgi.ini
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    links:
      - website
      - flower
    volumes_from:
      - website:ro
    ports:
      - "80:80"
      - "443:443"
    command: nginx -c nginx.conf
    restart: always

  rabbit:
    image: rabbitmq:latest
    env_file:
      - ./flask.env

  flower:
    build:
      context: ..
      dockerfile: ./deployment/flower/Dockerfile
    environment:
      DISCOVER_RABBITMQ: 'true'
    depends_on:
      - rabbit
    links:
      - website
      - rabbit
    volumes_from:
      - website:ro
    command: flower
    restart: always

  worker:
    env_file:
      - ./flask.env
    build:
      context: ..
      dockerfile: ./deployment/celery/Dockerfile
    volumes_from:
      - website
    depends_on:
      - rabbit
    links:
      - website
      - rabbit
    command: celery -A app.celery worker -l info
    restart: always