version: '2'

services:
  website:
    build:
      context: ..
      dockerfile: ./deployment/report/Dockerfile
    ports:
      - '80:8080'
    command: python main.py
    volumes:
      - ../app:/app/app
      - ../instance/:/app/instance
      - ../database/app.db:/app/app.db
