version: '2'

services:
  # App
  website:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/flask/Dockerfile
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp

  # Web Server
  nginx:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    command: nginx -c nginx.conf
    volumes_from:
      - website:ro
    links:
      - website
    ports:
      - "80:80"
      - "443:443"

  # RabbitMQ Broker
  rabbit:
    hostname: "rabbit1"
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"

  # Celery worker
  worker:
    build:
      context: ..
      dockerfile: ./deployment/celery/Dockerfile
    hostname: "worker"
    restart: always
    command: celery -A app.celery worker -l info
    environment:
      user: "user"
      password: "password"
    volumes_from:
      - website:ro
    links:
      - website
      - rabbit
    depends_on:
      - rabbit