version: '2'

services:
  # App
  website:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/flask/Dockerfile
    command: uwsgi --ini uwsgi.ini
    env_file:
      - ./flask.env
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp

  # Web Server
  nginx:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    command: nginx -c nginx.conf
    volumes_from:
      - website:ro
    links:
      - website
    ports:
      - "80:80"
      - "443:443"

  # RabbitMQ Broker
  rabbit:
    image: rabbitmq:latest
    env_file:
      - ./flask.env

  # Celery worker
  worker:
    build:
      context: ..
      dockerfile: ./deployment/celery/Dockerfile
    restart: always
    command: celery -A app.celery worker -l info
    env_file:
      - ./flask.env
    volumes_from:
      - website
    links:
      - website
      - rabbit
    depends_on:
      - rabbit