version: '2'

services:
  website:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    env_file:
      - ./flask.env
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp
    command: uwsgi --ini uwsgi.ini
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - website
      - flower
    volumes_from:
      - website:ro
    ports:
      - "80:80"
      - "443:443"
    command: nginx -c nginx.conf
    restart: always

  rabbitmq:
    image: 'rabbitmq:3.6'
    networks:
      local:
        aliases:
          - rabbitmq.local

  etcd:
    image: 'quay.io/coreos/etcd'
    entrypoint: /usr/local/bin/etcd
    command: [
      '--name', 'etcd0',
      '--advertise-client-urls','http://etcd.local:2379,http://etcd.local:4001',
      '--listen-client-urls', 'http://0.0.0.0:2379,http://0.0.0.0:4001',
      '--initial-advertise-peer-urls', 'http://etcd.local:2380',
      '--listen-peer-urls', 'http://0.0.0.0:2380',
      '--initial-cluster-token', 'etcd-cluster-1',
      '--initial-cluster', 'etcd0=http://etcd.local:2380',
      '--initial-cluster-state', 'new',
    ]

    networks:
      local:
        aliases:
          - etcd.local
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
