version: '2'

services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: python main.py
    volumes:
      - ../app:/app/app
      - ../instance/:/app/instance
      - ../database/app.db:/app/app.db
