version: '2'

services:
  website:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/flask/Dockerfile
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp
  nginx:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    command: nginx -c nginx.conf
    volumes_from:
      - website:ro
    links:
      - website
    ports:
      - "80:80"
      - "443:443"
