version: '2'

services:
  website:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/app/Dockerfile
    command: uwsgi --ini app.ini
    volumes:
      - ../app:/app/app
      - ../database/app.db:/app/app.db
      - ../instance:/tmp
  nginx:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    command: nginx -c /etc/nginx/nginx.conf
    volumes_from:
      - website:ro
    links:
      - website
    ports:
      - "80:80"
      - "443:443"
