version: '2'

services:
  # App
  website:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/flask/Dockerfile
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ../app:/var/www/app/app
      - ../database:/var/www/app/database
      - ../instance:/var/www/tmp

  # Web Server
  nginx:
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    command: nginx -c nginx.conf
    volumes_from:
      - website:ro
    links:
      - website
    ports:
      - "80:80"
      - "443:443"

  # RabbitMQ Broker
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # port for debugging
      - "15672:15672"  # port for rabbitmq management plugin

  # Celery worker
  worker:
    build:
      context: ..
      dockerfile: ./deployment/celery/Dockerfile
    volumes_from:
      - website:ro
    links:
      - website
      - rabbit
    depends_on:
      - rabbit